CREATE  TABLE "ORGANISATION"(
    "ID" INTEGER NOT NULL,
    "ABN" VARCHAR(11) NOT NULL,
    "NAME" VARCHAR(255) NOT NULL
);

	CREATE  TABLE "CONTACT"(
    "ID" INTEGER NOT NULL,
    "CREATED" TIMESTAMP,
    "FIRST_NAME" VARCHAR(30) NOT NULL,
    "LAST_NAME" VARCHAR(30) NOT NULL,
    "ORGANISATION_ID" INTEGER
);